### ISSUE TITLE
Description, ReadMe or wiki ?

### ISSUE THREAD

**Issue by pepperstreet** [joomtools/plg_fields_jtautofillfromcf#1]
Hello, just came here by accident. Would you mind to explain briefly the functionality or use case for this field. The title sounds interesting. Thanks in advance.

**Comment by degobbis** [comment]
Hello, this field was a commissioned work.

It is used to copy the content of custom fields from the user management into a custom field of an article.
This is only valid the first time it is called, once the value is saved it is considered custom and can be changed at any time anyway.

The use case was a job market, where the user also included all information of the company, like address, company name, contact person ...

The article was then a job offer where these values were used again and again. In order not to copy this over and over again, I programmed this field.

It works only then, with the contents of the fields of the respectively logged in user.

I hope that helps for the better understanding.
